mysql:
  host: "119.91.64.41"
  port: 3308
  db: "blog"
  user: "root"
  password: "jm8812..."
#  database: "test"
  log_level: dev #当前日志环境

logger:
  level: info
  prefix: "[blog]"
  directory: "log"
  show_line: true
  log_in_console: true

system:
  host: "0.0.0.0"
  port: 8080
  env: dev #当前开发环境